sudo: false
cache: bundler
language: ruby
script:
 - RAILS_ENV=test bundle exec rake --trace db:migrate spec
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler
env:
  - RAILS_ENV=test RACK_ENV=test
rvm:
  - 2.3.0
notifications:
  email: false
